apiVersion: apps/v1
kind: Deployment
metadata:
  name: openflights-deployment
  labels:
    app: openflights
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openflights
  template:
    metadata:
      labels:
        app: openflights
    spec:
      containers:
      - name: openflights
        image: open-flights
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: openflights-secret
              key: secret_key
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: openflights-secret
              key: database_url